---
title: "actg175"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{actg175}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message = FALSE}
library(survival)
library(dplyr)
library(speff2trial)
library(devtools)
library(survRM2)
library(smim)
library(purrr)
# load_all()
```

# Data Cleanning 

* Pattern
  + 1: observed event time
  + 2: MAR imputation
  + 3: MNAR imputation 

* Delta
  + 1: no adjustment 
  + larger than 1: hazard is larger than MAR
  + less than 1: hazard is smaller than MAR
  
```{r}
data(ACTG175)

db <- ACTG175 %>% subset(drugs == 0 & strat == 1)
db <- db %>% mutate(time = days / 30.25, 
              status = cens, 
              group = arms, 
              pattern = ifelse(status == 1, 1, ifelse(time >= 24, 2, 3))) %>% 
         subset(group %in% c(0, 1)) %>% 
         mutate(group = ifelse(group == 0, 0, 1) )

fit <- survfit(Surv(time, status) ~ group, data = db )
plot(fit)

time <- db$time
status <- db$status
group <- db$group
pattern <- db$pattern
x <- db %>% select(age, cd40, symptom, )
tau <- 2 * 12
# db0 <- db %>% select(time, status, sex, log_thick)
# fit <- coxph(Surv(time, status) ~ rep(1, nrow(db0)), data = db0, x = TRUE, y = TRUE)
```


# MAR analysis 
```{r}
rmst2(time, status, group, tau= tau)
```

```{r, message = FALSE}
fit <- survfit(Surv(time, status) ~ group, data = db)
# Visualize with survminer
plot(fit, col = c(1,2))
```

# Delta Adjusted Imputation (MCAR) 

## RMST within group
```{r}
delta   <- c(1,1,1)[pattern]  # the third number control delta adjustment for MNAR 
tmp <- rmst_delta(time, status, x = rep(1, length(time)), group, pattern, delta, tau, n_mi = 5, n_b = 100, seed = 1234)
tmp$rmst
```

## RMST between group
```{r}
diff_rmst <- function(rmst, sd){
  diff <- diff(rmst)
  diff_sd <- sqrt( sum(sd^2) )
  p_val <- 2* (1 - pnorm( abs(diff/diff_sd) ))
  c(diff = diff, sd = diff_sd, p = p_val)
}

rbind( diff_rmst(tmp$rmst[,"rmst"], tmp$rmst[, "sd"]), 
       diff_rmst(tmp$rmst[,"rmst"], tmp$rmst[, "wb_sd"]))
```

## Survival Curve After Imputation 
```{r}
u_time <- sort(unique(time))
plot(tmp$surv[[1]][, "time"], tmp$surv[[1]][, "survival"], type = "l")
lines(tmp$surv[[2]][, "time"], tmp$surv[[2]][, "survival"], col = 2)
```

# Delta Adjusted Imputation (MNAR) 

## RMST within group
```{r}
.delta <- c(1, 2, 3, 4)
res <- map(.delta, function(delta0){
  delta   <- ifelse(group == 0, c(1,1,1)[pattern], c(1,1,delta0)[pattern])  # the third number control delta adjustment for MNAR 
  tmp <- rmst_delta(time, status, x = x, group, pattern, delta, tau, n_mi = 10, n_b = 100, seed = 111)
  tmp
})
res0 <- map(res, function(x) as.data.frame(x$rmst)) 
names(res0) <- .delta
res0 <- bind_rows(res0, .id = "delta")
```

```{r}
res0 %>% mutate(
  lower = rmst - 1.96 * sd, 
  upper = rmst + 1.96 * sd,
  lower_wb = rmst - 1.96 * wb_sd,
  upper_wb = rmst + 1.96 * wb_sd
) %>% mutate_if(is.numeric, formatC, digits = 2, format = "f")
```

## RMST between group
```{r}
diff_rmst <- function(data){
  rmst <- data$rmst
  sd <- data$sd
  diff <- diff(rmst)
  diff_sd <- sqrt( sum(sd^2) )
  p_val <- 2* (1 - pnorm( abs(diff/diff_sd) ))
  print(c(diff = diff, sd = diff_sd, p = p_val))
  return(1)
}

res0 %>% group_by(delta) %>% summarise(
  diff_rmst = diff(rmst), 
  diff_sd = sqrt( sum(sd^2) ), 
  diff_wb_sd = sqrt(sum(wb_sd^2)),
  lower = diff_rmst - 1.96 * diff_sd,
  upper = diff_rmst + 1.96 * diff_sd,
  p_val = 2* (1 - pnorm( abs(diff_rmst/diff_sd) )),
  lower_wb = diff_rmst - 1.96 * diff_wb_sd, 
  upper_wb = diff_rmst + 1.96 * diff_wb_sd,
  p_val_wb = 2* (1 - pnorm( abs(diff_rmst/diff_wb_sd) )),
) %>% mutate_if(is.numeric, formatC, digits = 3, format = "f")
```

